[project]
name = "router"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "you@example.com" }
]
requires-python = ">=3.14"
dependencies = [
    "datasets>=5.0.1",
    "fastapi[standard]>=0.141.1",
    "instructor>=1.17.0",
    "ollama>=0.6.2",
    "openai>=3.3.0",
    "pydantic>=2.13.5",
]

[project.scripts]
router = "router:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "basedpyright>=1.40.1",
]

[tool.basedpyright]
typeCheckingMode = "strict"
pythonVersion = "3.14"
include = ["src"]
